#!/bin/bash
# Auto-commit hook for .claude changes
# Called by Claude Code when skills, agents, or context are modified

set -e

CHANGE_TYPE=${1:-"update"}
CHANGED_PATH=${2:-""}
WORKSPACE_DIR=${WORKSPACE:-/workspace}

cd "$WORKSPACE_DIR" || exit 1

# Stage .claude changes (excluding sensitive context)
git add .claude/CLAUDE.md .claude/settings.json
git add .claude/skills/ .claude/agents/ .claude/commands/ .claude/prompts/
git add .claude/hooks/

# Create commit message based on change type
case $CHANGE_TYPE in
  "skill_created")
    MSG="[auto] skill: Add new skill - $(basename "$CHANGED_PATH")"
    ;;
  "agent_created")
    MSG="[auto] agent: Add new agent - $(basename "$CHANGED_PATH")"
    ;;
  "context_updated")
    # Only commit non-sensitive context (templates)
    MSG="[auto] context: Update context templates"
    ;;
  "command_created")
    MSG="[auto] command: Add new command - $(basename "$CHANGED_PATH")"
    ;;
  *)
    MSG="[auto] Update .claude configuration"
    ;;
esac

# Check if there are changes to commit
if git diff --cached --quiet; then
  echo "No changes to commit"
  exit 0
fi

# Commit
git commit -m "$MSG

Generated by AIPA (Blu)

Co-Authored-By: Blu <blu@aipa.local>"

# Push to remote
git push origin main || {
  echo "Push failed, will retry later"
  exit 0
}

echo "Successfully committed and pushed: $MSG"
